command:
  - "streamlit"
  - "run"
  - "app.py"
env:
  - name: "LAKEBASE_DB_NAME"
    value: "tannerw-adtech-db"
  - name: "POSTGRES_GROUP"
    value: "Tanner W Adtech DB Access Role"
  - name: "AGENT_ENDPOINT"
    value: "databricks-claude-3-7-sonnet"
