command:
  - "gunicorn"
  - "-w"
  - "1"
  - "-k"
  - "sync"
  - "-t"
  - "120"
  - "dash_app:server"
env:
  - name: "LAKEBASE_DB_NAME"
    value: "tannerw-adtech-db"
  - name: "POSTGRES_GROUP"
    value: "Tanner W Adtech DB Access Role"
  - name: "AGENT_ENDPOINT"
    value: "chat_history_agent_postgres_genie"
  - name: "AGENT_CHAT_K"
    value: "5"
  - name: "OBJC_DISABLE_INITIALIZE_FORK_SAFETY"
    value: "YES"
